-- ThinkPad T490 hardware profile
MONITOR1 = "eDP-1"
PRIMARY_MONITOR = MONITOR1
MONITOR_MODE = "1920x1080@60"
MONITOR_POSITION = "auto"
MONITOR_SCALE = "1"
ENABLE_MONITOR_FALLBACK = true
LID_SWITCH = "Lid Switch"
