-- Monitor wiki: https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Values come from the machine profile generated by the migration script.
hl.monitor({
    output = MONITOR1,
    mode = MONITOR_MODE,
    position = MONITOR_POSITION,
    scale = MONITOR_SCALE,
})

-- Machine profiles can use this to pick up additional displays without
-- assigning static connector names. The explicit primary rule remains more
-- specific.
if ENABLE_MONITOR_FALLBACK then
    hl.monitor({
        output = "",
        mode = "preferred",
        position = "auto",
        scale = "auto",
    })
end

-- Only disable the internal panel on lid close when an external monitor is
-- already active. This avoids a black session when the laptop is undocked.
-- Reopening the lid restores the panel at an automatic, non-overlapping
-- position. Confirm the switch name with `hyprctl devices` after first login.
if LID_SWITCH ~= "" then
    local lidCommand = "$HOME/.config/hypr/scripts/lid-monitor.sh "
        .. MONITOR1 .. " " .. MONITOR_MODE .. " " .. MONITOR_SCALE
    hl.bind("switch:on:" .. LID_SWITCH,
        hl.dsp.exec_cmd(lidCommand .. " close"), { locked = true })
    hl.bind("switch:off:" .. LID_SWITCH,
        hl.dsp.exec_cmd(lidCommand .. " open"), { locked = true })
end
